
<?php include 'components/includes.css.php' ?>

<style>
    select.form-control-user .placeholder {
    color: #a9a9a9; /* Light gray placeholder color */
}

</style>
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <?php include 'components/sidebar.php';?>
        <?=sidebar('addcase')?>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <?php require('components/top-navbar.php') ?>
                <?=topNavbar($userData["first_name"], $userData["last_name"])?>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Lists of Cases</h1>
                        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                                class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
                    </div>

                    <!-- Content Row -->
                    <div class="row">
                         <!-- Table -->
                         <div class="col-xl-12 col-lg-12">
                            <!-- DataTales Example -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">Lists of Cases</h6>
                                </div>
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                            <thead class="bg-gradient-dark text-white" style="font-size: 0.8rem;">
                                                <tr>
                                                    <th>Case ID</th>
                                                    <th>Case Title</th>
                                                    <th>Case Description</th>
                                                    <th>Client Name</th>
                                                    <th>Client Address</th>
                                                    <th>Client Gender</th>
                                                    <th>Client Age</th>
                                                    <th>Case Purok</th>
                                                    <th>Case Barangay</th>
                                                    <th>Generated By</th>
                                                    <th>Category</th>
                                                    <th>Severity</th>
                                                    <th>Status</th>
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                            <tfoot style="font-size: 0.8rem;">
                                                <tr>
                                                    <th>Case ID</th>
                                                    <th>Case Title</th>
                                                    <th>Case Description</th>
                                                    <th>Client Name</th>
                                                    <th>Client Address</th>
                                                    <th>Client Gender</th>
                                                    <th>Client Age</th>
                                                    <th>Case Purok</th>
                                                    <th>Case Barangay</th>
                                                    <th>Generated By</th>
                                                    <th>Category</th>
                                                    <th>Severity</th>
                                                    <th>Status</th>
                                                    <th>Action</th>
                                                </tr>
                                            </tfoot>
                                            <tbody id="tbody" style="font-size: 0.8rem;">
                                                <?php foreach($caseDatas as $caseData): ?>
                                                    <tr>
                                                        <td><?=$caseData["case_id"]?></td>
                                                        <td><?=$caseData["case_title"]?></td>
                                                        <td><?=$caseData["case_description"]?></td>
                                                        <td><?=$caseData["client_fname"]?> <?=$caseData["client_lname"]?></td>
                                                        <td><?=$caseData["client_address"]?></td>
                                                        <td><?=$caseData["gender"]?></td>
                                                        <td><?=$caseData["age"]?></td>
                                                        <td><?=$caseData["purok_name"]?></td>
                                                        <td><?=$caseData["barangay_name"]?></td>
                                                        <td><?=$caseData["first_name"]?> <?=$caseData["last_name"]?></td>
                                                        <td><?=$caseData["case_category_name"]?></td>
                                                        <td><?=$caseData["case_severity"]?></td>
                                                        <td><?=$caseData["status"]?></td>
                                                        <td>
                                                            <a href="case?action=archive-row&&row-id=<?php echo htmlspecialchars($caseData['case_id'])?>">Archive</a>
                                                            <a href="case?action=update-status&&row-id=<?php echo htmlspecialchars($caseData['case_id'])?>">Edit</a>
                                                        </td>
                                                    </tr>
                                                <?php endforeach ?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <?php include 'components/footer.html';?>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>


    <!-- Modal for Each Opened Barangay -->
    <!-- Modal -->
    <!-- <div class="modal fade" id="open_barangay" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="title">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            <div class="modal-body" id="modal_body">
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
            </div>
        </div>
    </div> -->

    <!-- <script>
        async function show_data(id) {
            console.log(id)
            try {
            const response = await fetch(`http://localhost/mental-health-management-system/api/barangay?id=${id}`);

            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }

            const data = await response.json();

            // Clear existing modal content before appending new data
            const modalBody = document.querySelector("#modal_body");
            modalBody.innerHTML = ''; // This removes all existing children of the modal body

            // Set the title
            document.querySelector("#title").textContent = data.length > 0 ? data[0].barangay_name : 'N/A';

            // Append new data to the modal body
            for (let d of data) {
                const p = document.createElement('p');
                const p2 = document.createElement('p');
                p.textContent = d.purok_name || 'No Purok Name';
                p2.textContent = `Case Count : ${d.case_count}` || 'No Case';
                modalBody.appendChild(p);
                modalBody.appendChild(p2);
            }
        } catch (error) {
            console.error('Error fetching barangay data:', error);
            // Display error message to the user if needed
            document.querySelector("#errorMessage").textContent = "Failed to load data.";
        }

        }
    </script> -->



    <!-- Logout Modal-->
    <?php include 'components/logout.modal.html';?>

    <?php include 'components/scripts.html';?>


    

</body>

</html>